version: '2.1'

services:
  micro-mall-backend:
    image: micro-mall-backend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9002:9002
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js